[theme]
# This base mode will auto-switch based on user's system preference
base = "auto"

primaryColor = "#0A192F"
backgroundColor = "#F3F4F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1F2937"
font = "monospace"

[theme.colors]
accentColor = "#FF4C29"
linkColor = "#2563EB"

[darkTheme]
primaryColor = "#0A192F"
backgroundColor = "#0D1117"            # Dark GitHub-style background
secondaryBackgroundColor = "#161B22"   # Card/background
textColor = "#F8F8F2"                  # Bright white text
font = "monospace"

[darkTheme.colors]
accentColor = "#FF7849"                # Coral-orange for highlights
linkColor = "#60A5FA"                  # Soft blue links
