[theme]
base="light"
primaryColor="#0A192F"       # Deep navy
backgroundColor="#FDFDFD"    # Light background
secondaryBackgroundColor="#FFFFFF"
textColor="#1F2937"          # Dark slate
font="monospace"

[theme.colors]
accentColor="#FF4C29"        # Bold red-orange
linkColor="#2563EB"          # Techy blue
